### ISSUE TITLE
More dialog info instead of popup card

### ISSUE THREAD

**Issue by SciTii** [thomasloven/lovelace-popup-card#19]
My Home Assistant version: 0.90.2

My lovelace configuration method (GUI or yaml): yaml

What I am doing:

Using exact same configuration as on older version of hassio with popup card and it was working perfectly. 

What I expected to happen:

After Upgrading it doesnt work anymore. more dialog info is not a popup card anymore. Using custom updater so i have the newest version of popupcard and card tool

What happened instead:

More dialog info came back. instead of popup card. I even tried second instance of hassio. same problem

**Minimal** steps to reproduce:

```yaml

title: My awesome lovelace interface
resources:
  - url: /local/github/thomasloven/card-tools.js?track=true
    type: js
  - url: /local/github/thomasloven/popup-card.js?track=true
    type: js
views:
  - title: My view
    icon: mdi:home-assistant
    popup_cards:
      light.swiatlo1:
        title: Bedside lamp settings
        card:
          type: entities
          entities:
            - light.swiatlo2
    cards:
      - type: entities
        entities:
          - light.swiatlo1


# End of code
```

Error messages from the browser console:

---

`By putting an X in the boxes ([ ]) below, I indicate that I:`

[x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[x] Have made sure I am using the latest version of popup-card.

[x] Have made sure I am using the latest version of [card-tools](https://github.com/thomasloven/lovelace-card-tools).

[x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
