### ISSUE TITLE
Scrolling

### ISSUE THREAD

**Issue by rollover77** [thomasloven/lovelace-popup-card#20]
****Sorry, how do I format the code to not appear as one huge block?**

My Home Assistant version: 0.90.0

My lovelace configuration method (GUI or yaml):
```yaml
      media_player.living_room:  # LIVING ROOM MEDIA PLAYER POPUP
        title: Apple TV
        card:
          type: vertical-stack
          cards:
            - type: entities
              entities:
                - type: media-control
                  entity: media_player.living_room
                - type: custom:mini-media-player
                  entity: media_player.sonos
                  more_info: false
                  artwork: full-cover-fit
                  idle_view:
                    when_idle: true
                  hide:
                    power: true
                    name: true
                    controls: true
                    icon: true
                    source: true
                    artwork_border: true 
            - type: picture-elements
              image: /local/images/short-empty.png?v2.2
              elements:
                - type: image # Watch TV Button + STYLE ANCHOR
                  entity: switch.living_room_tv
                  tap_action:
                    action: toggle
                  image: /local/images/remote/tv.svg?v1
                  state_filter:
                    "on": invert(.5) sepia(1) saturate(8) hue-rotate(10deg)
                  style:
                    top: 50%
                    left: 20%
                    # Reuse these values with <<: *style_anchor in the style section for each button
                    <<: &style_anchor
                      width: 2em
                      height: 2em
                      padding: 15px
                      background-color: var(--paper-item-icon-color)
                      border-radius: 50%
                      box-shadow: 0 3px 5px -1px rgba(0,0,0,.2), 0 6px 10px 0 rgba(0,0,0,.14), 0 1px 18px 0 rgba(0,0,0,.12)
                - type: image #Apple TV Button
                  entity: switch.apple_tv
                  tap_action:
                    action: toggle
                  image: /local/images/remote/apple.svg?v1
                  state_filter:
                    "on": invert(.5) sepia(1) saturate(8) hue-rotate(10deg)
                  style:
                    <<: *style_anchor
                    top: 50%
                    left: 50%
                - type: image # Start PS4 Button
                  entity: switch.ps4
                  tap_action:
                    action: toggle
                  image: /local/images/remote/playstation.svg?v1
                  state_filter:
                    "on": invert(.5) sepia(1) saturate(8) hue-rotate(10deg)
                  style:
                    <<: *style_anchor
                    top: 50%
                    left: 80% 
            - type: conditional # Display volume controls when any Activity is on
              conditions:
              - entity: remote.living_room_hub
                state: "on"
              card:
                type: picture-elements
                image: /local/images/short-empty.png?v2.1
                elements:
                - type: image  # Volume Up
                  tap_action:
                    action: call-service
                    service: remote.send_command
                    service_data:
                      entity_id: remote.living_room_hub
                      device: 60032870
                      command: VolumeUp
                  image: /local/images/remote/volup.svg?v1
                  style:
                    <<: *style_anchor
                    top: 50%
                    left: 80%
                - type: image  # Mute
                  tap_action:
                    action: call-service
                    service: remote.send_command
                    service_data:
                      entity_id: remote.living_room_hub
                      device: 60032870
                      command: Mute
                  image: /local/images/remote/mute.svg?v1
                  style:
                    <<: *style_anchor
                    top: 50%
                    left: 50%
                - type: image  # Volume Down
                  tap_action:
                    action: call-service
                    service: remote.send_command
                    service_data:
                      entity_id: remote.living_room_hub
                      device: 60032870
                      command: VolumeDown
                  image: /local/images/remote/voldown.svg?v1
                  style:
                    <<: *style_anchor
                    top: 50%
                    left: 20%
```

What I am doing:
The pop up works great, however some of the content is below the end of the screen and I'm not able to scroll down to see the rest of it. Any suggestions for what I should change?
Many thanks
