### ISSUE TITLE
Switch position (light, input booleans...) and sensor icon not refreshed correctly

### ISSUE THREAD

**Issue by Oriondely** [thomasloven/lovelace-popup-card#27]
Hello,
first of all.. thank you for your great work !

I have a problem with popup-card in my HA, ver. 0.91.0
OS: Windows 10
Browser: Chrome

When I switch ON a light or input boolean in a popup card, the switch works correctly in HA, but it reverts back to OFF after a couple of seconds in the initial position in the popup-card.

The light icon is not showed correctly in popup-card, but it's showed correctly in glances card.

These are the steps followed (images attached):
01 - Light is OFF
02 - Turning light ON
03 - Light is ON but turns OFF automatically in the popup card after a couple of seconds (not correct)
04 - In the glance card Light is ON (correct)
05 - If I open popup card light is ON (correct)

I have the same issue also with input boolean switches.
Am I doing something wrong?
Thank you

This is the lovelace configuration used:
```yaml
resources:
  - url: /local/card-tools/card-tools.js?v=0.4
    type: js
  - url: /local/more-info-card/more-info-card.js
    type: js
  - url: /local/popup-card/popup-card.js
    type: js    
  - url: /local/fold-entity-row/fold-entity-row.js
    type: js
  - url: /local/card-modder/card-modder.js
    type: js
  - url: /local/time-input-row/time-input-row.js
    type: js
  - url: /local/dual-gauge-card/dual-gauge-card.js
    type: js
  - url: /local/vertical-stack-in-card/vertical-stack-in-card.js?v=0.1.2
    type: js
  - url: /local/bar-card/bar-card.js?v=0.1.9.7.1
    type: js
  - url: /local/mini-graph-card-bundle/mini-graph-card-bundle.js?v=0.3.3
    type: js
  - url: /local/slider-entity-row/slider-entity-row.js
    type: js
  - url: /local/button-card/button-card.js
    type: js
  - url: /local/popup-scroll-fix/popup.js
    type: js

# popup_cards Section
views:
  - title: Zona Giorno
    icon: 'mdi:weather-sunny'
    panel: false
    path: default_view
    badges: []
    popup_cards:
      light.01_ingresso_1_corridoio:
        title: Luci 01 Ingresso
        large: true
        card:
          type: entities
          show_header_toggle: false
          entities:
            - type: custom:more-info-card
              entity: light.01_ingresso_1_corridoio
            - type: custom:more-info-card
              entity: light.01_ingresso_2_zona_giorno
            - type: custom:more-info-card
              entity: light.01_ingresso_3_zona_notte

#cards Section
    cards:
      - type: custom:vertical-stack-in-card
        title: Ingresso
        cards:
        - type: glance
          columns: 2
          show_icon: true
          show_name: false
          show_state: true
          entities:
            - entity: light.01_ingresso_1_corridoio
            - entity: input_select.ismart_alarm
```

![01 - Light is OFF](https://user-images.githubusercontent.com/33926779/60265757-ccf4b500-98e6-11e9-9568-104208816998.png)
![02 - Turning Light ON](https://user-images.githubusercontent.com/33926779/60265759-ccf4b500-98e6-11e9-9a72-a47800e6dcca.png)
![03 - Light is ON but turns OFF automatically (not correct)](https://user-images.githubusercontent.com/33926779/60265761-cd8d4b80-98e6-11e9-8687-65373da2bd11.png)
![04 - In the glance card Light is ON (correct)](https://user-images.githubusercontent.com/33926779/60265762-cd8d4b80-98e6-11e9-9a61-10234b674746.png)
![05 - If I open popup card light is ON (correct)](https://user-images.githubusercontent.com/33926779/60265763-cd8d4b80-98e6-11e9-8b08-c3d753d7fc70.png)
