### ISSUE TITLE
Can't use this with custom:banner-card

### ISSUE THREAD

**Issue by miguelarios** [thomasloven/lovelace-popup-card#29]
My Home Assistant version: 0.97.0

My lovelace configuration method (GUI or yaml): yaml

What I am doing:
trying to display a custom:dual-thermostat as a popup while using custom:banner-card to display my living room entities.

What I expected to happen:
a dual thermostat card appear

What happened instead:
no custom:dual thermostat card just the normal climate card for 1 of my entities

**Minimal** steps to reproduce:
Well I would say you need to have the dual thermostat, banner card, and try the pop. Can't see how else to reproduce. Maybe with a custom card?

```yaml
# The least ammount of code possible to reproduce my error

path: mobile_home
title: Mobile
icon: mdi:home
popup_cards:
  climate.trane_corporation_model_tcont624as42daa_cooling_1:
    title: Downstairs Thermostat
    card:
      type: entities
      entities:
        - type: custom:dual-thermostat
          name: Downstairs
          entities:
          - entity: climate.trane_corporation_model_tcont624as42daa_cooling_1
            type: cool
          - entity: climate.trane_corporation_model_tcont624as42daa_heating_1
            type: heat
          fan_control: true
          min_slider: 60
          max_slider: 80
cards:
- type: custom:banner-card
  heading: "Living Room"
  background: "#f0ffff"
  entities:
    - entity: sensor.house_mode
      name: A&M
    - entity: climate.trane_corporation_model_tcont624as42daa_cooling_1
      name: Temperature
      attribute: current_temperature
    - entity: light.jasco_products_14294_in_wall_smart_dimmer_level_2
      name: Ceiling
    - entity: light.living_room
      name: Lamps

# End of code
```

Error messages from the browser console:

2019-08-22 12:38:45 ERROR (MainThread) [frontend.js.latest.201908050] https://1ew1eroute9eloklzo09iv9e0loekip1.ui.nabu.casa/local/plugins/dual-thermostat/dual-thermostat.js?v=1:174:90343 Error: Specify cool and heat entities from within the climate domain.

---

`By putting an X in the boxes ([ ]) below, I indicate that I:`

- [X ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of popup-card.
- [X] Have made sure I am using the latest version of [card-tools](https://github.com/thomasloven/lovelace-card-tools).
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
